sudo: false

language: node_js

node_js:
  - "0.12"

install: 
  - npm install -g grunt-cli
  - npm install grunt grunt-bower-task

script: grunt

after_success:
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" && $TRAVIS_BRANCH == \"master\" ]] && chmod +x deploy_ghpages.sh && ./deploy_ghpages.sh"